name: Continuous Integration

on:
  push:
    branches: [main, '001-babble-web-app']
  pull_request:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  set-build-variables:
    uses: ./.github/workflows/set-build-variables.yml

  lint-markdown:
    uses: ./.github/workflows/lint-markdown.yml

  build-backend:
    needs: [set-build-variables]
    uses: ./.github/workflows/build-and-publish-backend-service.yml
    with:
      version: ${{ needs.set-build-variables.outputs.semVer }}

  build-frontend:
    needs: [set-build-variables]
    uses: ./.github/workflows/build-and-publish-frontend-app.yml
    with:
      version: ${{ needs.set-build-variables.outputs.semVer }}
