name: Set Build Variables

on:
  workflow_call:
    outputs:
      semVer:
        description: 'Semantic version'
        value: ${{ jobs.set-variables.outputs.semVer }}

jobs:
  set-variables:
    runs-on: ubuntu-latest
    outputs:
      semVer: ${{ steps.gitversion.outputs.semVer }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v3
        with:
          versionSpec: '6.x'

      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v3
